spring:
  application:
    name: mock-psp
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mockpsp}
    username: ${DB_USERNAME:ledgerpay}
    password: ${DB_PASSWORD:ledgerpay}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
